### ISSUE TITLE
POST sur /tests/voice renvoi un 404

### ISSUE THREAD

**Issue by Save92** [FPierre/dot_api#101]

**Comment by FPierre** [comment]
Elle existe et est accessible.

curl -X POST -H "Cache-Control: no-cache" -H "Postman-Token: bf9d6017-c040-b6a2-186c-641b7efeebfc" "http://dot-api.fpierre.ovh/api/v1/tests/voice?user_email=njournaud@hotmail.fr&user_token=HfMtQaAVxrkydm2JSGSL"


Merci de pas m'ouvrir des issues sans bien vérifier :) (ça me fout la pression pour rien là)
