### ISSUE TITLE
Aucune récupération des informations lié à sarah  sur smartphone

### ISSUE THREAD

**Issue by tasa95** [FPierre/dot_api#119]
Problème ; via un client Rest j'arrive bien a récupérer des informations sur les rasps.
[Lien](https://drive.google.com/open?id=0B_SEQQJPILeNTnNvRDB3MVBBZ28
)
Par contre aucune information est présente sur la web app : 
[Lien](https://drive.google.com/open?id=0B_SEQQJPILeNMmkzc0hZakVES1k)

**Comment by FPierre** [comment]
[Commit](f6b2944046f4ab61de33809ac5180b3a1277a30c)
