### ISSUE TITLE
Flèches présentes sur la page de mémo alors que aucun mémo supplémentaire est disponible

### ISSUE THREAD

**Issue by tasa95** [FPierre/dot_api#120]
dans la page des mémos, Les flèches pour changer de page sont présents alors qu'il y a pas l'air d'avoir plus de mémo : 

[Image](https://drive.google.com/open?id=0B_SEQQJPILeNaTg2ZE95V3V4NFE)

**Comment by FPierre** [comment]
Similaire à ce [ticket](https://github.com/FPierre/dot_api/issues/47)

**Comment by FPierre** [comment]
[Commit](401d8bcd5fe06a8f6012aac02ffc2213a38ffd1c)
