### ISSUE TITLE
Enregistrement des mémos

### ISSUE THREAD

**Issue by tasa95** [FPierre/dot_api#122]
Aucune redirection ou indication précisant que le mémo a été enregistrée ... du coup j'ai flooder la page mémos : 
[Image](https://drive.google.com/open?id=0B_SEQQJPILeNN1Z4YmdJZFBmLUE)

**Comment by FPierre** [comment]
[Commit](ecc26a5ae8e269bd6778c7b53e7460ff9505cdc4)
