### ISSUE TITLE
Affichage en vertical légèrement tronqué sur la liste des Raspberry Pi

### ISSUE THREAD

**Issue by tasa95** [FPierre/dot_api#123]
Léger problème d'affichage en vertical sur le téléphone, Pas un énorme issue.
Faire un saut de ligne après le nom de la rasps

[Image](https://drive.google.com/open?id=0B_SEQQJPILeNSFJnU2pLNzJlWEU)

**Comment by FPierre** [comment]
[Commit](3df6b4b3ec75b2245b33a0e9e94e4b4d6bf597c3)
