### ISSUE TITLE
Problème au survol du menu de la web app

### ISSUE THREAD

**Issue by Save92** [FPierre/dot_api#134]
<img width="302" alt="capture d ecran 2016-07-08 a 20 24 33" src="https://cloud.githubusercontent.com/assets/4005371/16697471/0d561042-454a-11e6-8521-a3cfd6c4d219.png">
A partir de vocale et en dessous il me surligne le menu vocale quand ma souris est sur Parametres, il me surligne Parametres quand je suis sur Crédits et Crédits quand je suis sur déconnexion.
Quand je clique il me redirige bien vers la bonne page. Juste un bug d'affichage, priorité basse

**Comment by FPierre** [comment]
Bloquant, priorité haute plutôt
