### ISSUE TITLE
Put user

### ISSUE THREAD

**Issue by Save92** [FPierre/dot_api#84]
Un user peut modifier ses propriétés sans pour autant changer son mot de passe : 
Le mot de passe est optionnel dans le put (Pas passé en paramètre)

**Comment by Save92** [comment]
toujours message password doit etre remplie : 
--> PUT http://dot-api.fpierre.ovh/api/v1/users/7?user_token=dq7azsTpHj_x8PkUqrH3&user_email=io@io.fr http/1.1
Content-Type: application/json; charset=UTF-8
Content-Length: 140
{"admin":false,"approved":true,"email":"io@io.fr","firstname":"iou","lastname":"io","password":"","token":"dq7azsTpHj_x8PkUqrH3","userId":7}
--> END PUT (140-byte body)
<-- 422 Unprocessable Entity http://dot-api.fpierre.ovh/api/v1/users/7?user_token=dq7azsTpHj_x8PkUqrH3&user_email=io@io.fr (96ms)
{"password":["doit être rempli(e)"]}

Et d'ailleur on voit le admin:false approved true, eux ne peuvent pas etre modifier par le user lui meme mais que par un admin

**Comment by FPierre** [comment]
Password ne peut pas être "" !
