### ISSUE TITLE
Get settings

### ISSUE THREAD

**Issue by Save92** [FPierre/dot_api#85]
Get : GET http://dot-api.fpierre.ovh/api/v1/settings/1?user_token=****&user_email=io@io.fr (les **** pour ne pas mettre le token)
me retourne un 403 FORBIDDEN

**Comment by Save92** [comment]
Remarque : Il faut être admin pour avoir les settings?

**Comment by FPierre** [comment]
Ca devrait être bon maintenant

**Comment by Save92** [comment]
ok accès au settings mais erreur 500 lors de la modification du statut occupied

**Comment by FPierre** [comment]
Je suis en train de faire la connexion avec les Raspberry (pour les prévenir que la salle est occupée). C'est effectivement buggé

**Comment by Save92** [comment]
Besoin d'etre testé?
