### ISSUE TITLE
Quand le mode d'écran change, avertir le serveur par Websocket

### ISSUE THREAD

**Issue by FPierre** [FPierre/dot_api#91]
Pour cohérence des données sur la Web App

**Comment by FPierre** [comment]
Ou alors recharger la page des Settings Web App et Android plus souvent (pour être à jour part rapport à l'API ?)

**Comment by Save92** [comment]
Hum..... je sais pas trop... Tu prefererais que je check régulièrement si les settings ont changé?

**Comment by FPierre** [comment]
Ce ticket est un ticket API, il ne te concerne pas
